
module.exports = [    
        // alignment between keiser and our calculator
        {fever: 37.8, birthWeek: 36, plusDays: 1, rom: 9  , gbs: "positive", antibiotics: "broad-4", expectedResult: { eosStat: 0.67, wellAppearingEos: 0.28, equivocalEos: 3.36, clinicalIllnessEos: 14.09}},
        {"fever":36,"birthWeek":34,"plusDays":0,"rom":5,"gbs":"positive","antibiotics":"broad-4","expectedResult":{"eosStat":0.18,"wellAppearingEos":0.07,"equivocalEos":0.87,"clinicalIllnessEos":3.7}},
        {"fever":36,"birthWeek":35,"plusDays":1,"rom":15,"gbs":"positive","antibiotics":"broad-2","expectedResult":{"eosStat":0.11,"wellAppearingEos":0.05,"equivocalEos":0.56,"clinicalIllnessEos":2.38}},
        {"fever":37,"birthWeek":36,"plusDays":2,"rom":30,"gbs":"positive","antibiotics":"GBS-2","expectedResult":{"eosStat":0.34,"wellAppearingEos":0.14,"equivocalEos":1.71,"clinicalIllnessEos":7.2}},
        {"fever":38,"birthWeek":34,"plusDays":3,"rom":5,"gbs":"positive","antibiotics":"none","expectedResult":{"eosStat":8.67,"wellAppearingEos":3.57,"equivocalEos":41.92,"clinicalIllnessEos":156.48}},
        {"fever":36,"birthWeek":35,"plusDays":4,"rom":15,"gbs":"negative","antibiotics":"broad-4","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.02,"equivocalEos":0.2,"clinicalIllnessEos":0.85}},
        {"fever":36.1,"birthWeek":36,"plusDays":5,"rom":30,"gbs":"negative","antibiotics":"broad-2","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.02,"equivocalEos":0.19,"clinicalIllnessEos":0.79}},
        {"fever":37.1,"birthWeek":34,"plusDays":6,"rom":5,"gbs":"negative","antibiotics":"GBS-2","expectedResult":{"eosStat":0.29,"wellAppearingEos":0.12,"equivocalEos":1.46,"clinicalIllnessEos":6.16}},
        {"fever":38.1,"birthWeek":35,"plusDays":1,"rom":15,"gbs":"negative","antibiotics":"none","expectedResult":{"eosStat":4.77,"wellAppearingEos":1.96,"equivocalEos":23.43,"clinicalIllnessEos":92.32}},
        {"fever":36,"birthWeek":36,"plusDays":2,"rom":30,"gbs":"unknown","antibiotics":"broad-4","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.02,"equivocalEos":0.18,"clinicalIllnessEos":0.78}},
        {"fever":36.2,"birthWeek":39,"plusDays":3,"rom":5,"gbs":"unknown","antibiotics":"broad-2","expectedResult":{"eosStat":0.01,"wellAppearingEos":0,"equivocalEos":0.06,"clinicalIllnessEos":0.23}},
        {"fever":37.2,"birthWeek":40,"plusDays":4,"rom":15,"gbs":"unknown","antibiotics":"GBS-2","expectedResult":{"eosStat":0.09,"wellAppearingEos":0.04,"equivocalEos":0.44,"clinicalIllnessEos":1.86}},
        {"fever":38.3,"birthWeek":41,"plusDays":5,"rom":30,"gbs":"unknown","antibiotics":"none","expectedResult":{"eosStat":2.64,"wellAppearingEos":1.08,"equivocalEos":13.06,"clinicalIllnessEos":53.13}},
        {"fever":36,"birthWeek":39,"plusDays":6,"rom":5,"gbs":"positive","antibiotics":"broad-4","expectedResult":{"eosStat":0.01,"wellAppearingEos":0,"equivocalEos":0.06,"clinicalIllnessEos":0.26}},
        {"fever":36.4,"birthWeek":40,"plusDays":0,"rom":15,"gbs":"positive","antibiotics":"broad-2","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.02,"equivocalEos":0.2,"clinicalIllnessEos":0.84}},
        {"fever":37.4,"birthWeek":41,"plusDays":1,"rom":30,"gbs":"positive","antibiotics":"GBS-2","expectedResult":{"eosStat":0.32,"wellAppearingEos":0.13,"equivocalEos":1.6,"clinicalIllnessEos":6.75}},
        {"fever":38.4,"birthWeek":39,"plusDays":2,"rom":5,"gbs":"positive","antibiotics":"none","expectedResult":{"eosStat":1.68,"wellAppearingEos":0.69,"equivocalEos":8.36,"clinicalIllnessEos":34.5}},
        {"fever":36,"birthWeek":40,"plusDays":3,"rom":15,"gbs":"negative","antibiotics":"broad-4","expectedResult":{"eosStat":0.01,"wellAppearingEos":0,"equivocalEos":0.05,"clinicalIllnessEos":0.23}},
        {"fever":36.5,"birthWeek":41,"plusDays":4,"rom":30,"gbs":"negative","antibiotics":"broad-2","expectedResult":{"eosStat":0.05,"wellAppearingEos":0.02,"equivocalEos":0.25,"clinicalIllnessEos":1.07}},
        {"fever":37.5,"birthWeek":39,"plusDays":5,"rom":5,"gbs":"negative","antibiotics":"GBS-2","expectedResult":{"eosStat":0.08,"wellAppearingEos":0.03,"equivocalEos":0.41,"clinicalIllnessEos":1.72}},
        {"fever":38.5,"birthWeek":40,"plusDays":6,"rom":15,"gbs":"negative","antibiotics":"none","expectedResult":{"eosStat":1.94,"wellAppearingEos":0.8,"equivocalEos":9.64,"clinicalIllnessEos":39.62}},
        {"fever":36,"birthWeek":41,"plusDays":0,"rom":30,"gbs":"unknown","antibiotics":"broad-4","expectedResult":{"eosStat":0.02,"wellAppearingEos":0.01,"equivocalEos":0.09,"clinicalIllnessEos":0.37}},
        {"fever":36.6,"birthWeek":39,"plusDays":1,"rom":5,"gbs":"unknown","antibiotics":"broad-2","expectedResult":{"eosStat":0.02,"wellAppearingEos":0.01,"equivocalEos":0.1,"clinicalIllnessEos":0.44}},
        {"fever":37.6,"birthWeek":40,"plusDays":2,"rom":15,"gbs":"unknown","antibiotics":"GBS-2","expectedResult":{"eosStat":0.16,"wellAppearingEos":0.06,"equivocalEos":0.78,"clinicalIllnessEos":3.32}},
        {"fever":38.6,"birthWeek":41,"plusDays":3,"rom":30,"gbs":"unknown","antibiotics":"none","expectedResult":{"eosStat":3.8,"wellAppearingEos":1.56,"equivocalEos":18.73,"clinicalIllnessEos":74.87}},
        {"fever":36,"birthWeek":42,"plusDays":4,"rom":5,"gbs":"positive","antibiotics":"broad-4","expectedResult":{"eosStat":0.03,"wellAppearingEos":0.01,"equivocalEos":0.14,"clinicalIllnessEos":0.58}},
        {"fever":36.7,"birthWeek":42,"plusDays":5,"rom":15,"gbs":"positive","antibiotics":"broad-2","expectedResult":{"eosStat":0.15,"wellAppearingEos":0.06,"equivocalEos":0.76,"clinicalIllnessEos":3.22}},
        {"fever":37.7,"birthWeek":43,"plusDays":6,"rom":30,"gbs":"positive","antibiotics":"GBS-2","expectedResult":{"eosStat":2.11,"wellAppearingEos":0.87,"equivocalEos":10.45,"clinicalIllnessEos":42.85}},
        {"fever":38.7,"birthWeek":43,"plusDays":0,"rom":5,"gbs":"positive","antibiotics":"none","expectedResult":{"eosStat":7.67,"wellAppearingEos":3.16,"equivocalEos":37.23,"clinicalIllnessEos":140.85}},
        {"fever":36,"birthWeek":42,"plusDays":1,"rom":15,"gbs":"negative","antibiotics":"broad-4","expectedResult":{"eosStat":0.02,"wellAppearingEos":0.01,"equivocalEos":0.09,"clinicalIllnessEos":0.4}},
        {"fever":36.8,"birthWeek":42,"plusDays":2,"rom":30,"gbs":"negative","antibiotics":"broad-2","expectedResult":{"eosStat":0.11,"wellAppearingEos":0.04,"equivocalEos":0.55,"clinicalIllnessEos":2.31}},
        {"fever":37.8,"birthWeek":43,"plusDays":3,"rom":5,"gbs":"negative","antibiotics":"GBS-2","expectedResult":{"eosStat":0.49,"wellAppearingEos":0.2,"equivocalEos":2.45,"clinicalIllnessEos":10.32}},
        {"fever":38.8,"birthWeek":42,"plusDays":4,"rom":15,"gbs":"negative","antibiotics":"none","expectedResult":{"eosStat":5.97,"wellAppearingEos":2.46,"equivocalEos":29.16,"clinicalIllnessEos":112.97}},
        {"fever":36,"birthWeek":42,"plusDays":5,"rom":30,"gbs":"unknown","antibiotics":"broad-4","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.01,"equivocalEos":0.18,"clinicalIllnessEos":0.75}},
        {"fever":36.9,"birthWeek":43,"plusDays":6,"rom":5,"gbs":"unknown","antibiotics":"broad-2","expectedResult":{"eosStat":0.17,"wellAppearingEos":0.07,"equivocalEos":0.86,"clinicalIllnessEos":3.62}},
        {"fever":37.9,"birthWeek":43,"plusDays":0,"rom":15,"gbs":"unknown","antibiotics":"GBS-2","expectedResult":{"eosStat":0.69,"wellAppearingEos":0.28,"equivocalEos":3.43,"clinicalIllnessEos":14.37}},
        {"fever":38.9,"birthWeek":43,"plusDays":1,"rom":30,"gbs":"unknown","antibiotics":"none","expectedResult":{"eosStat":13.8,"wellAppearingEos":5.71,"equivocalEos":65.4,"clinicalIllnessEos":228.8}},
        {"fever":38,"birthWeek":40,"plusDays":0,"rom":30,"gbs":"negative","antibiotics":"none","expectedResult":{"eosStat":1.06,"wellAppearingEos":0.44,"equivocalEos":5.29,"clinicalIllnessEos":22.04}},
        {"fever":36,"birthWeek":35,"plusDays":4,"rom":15,"gbs":"negative","antibiotics":"broad-4","expectedResult":{"eosStat":0.04,"wellAppearingEos":0.02,"equivocalEos":0.2,"clinicalIllnessEos":0.85}}
]
